### ISSUE TITLE
Swift has been updated to 4.0

### ISSUE THREAD

**Issue by VineFiner** [mcdappdev/Vapor-Template#10]
Swift has been updated to 4.0，This is still 3.1，If you have time you want to update it.Thank you very much.

**Comment by jdmcd** [comment]
Hi, this should compile with Swift 4.0 but there may be warnings. I am currently working on upgrading the template to Vapor 3, so that will be the newest and recommended version to use when it's released.

**Comment by jdmcd** [comment]
@VineFiner the new version of this repo has been moved to https://github.com/gotranseo/template

**Comment by VineFiner** [comment]
Thank you
