### ISSUE TITLE
fatal error: Error raised at top level: Abort request error: Bad Request

### ISSUE THREAD

**Issue by emilagervigstarup** [mcdappdev/Vapor-Template#6]
I get this when build on my mac:

fatal error: Error raised at top level: Abort request error: Bad Request

Identifier: Vapor.Abort.badRequest: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 188
2017-05-23 20:10:26.439717+0200 Run[17621:613886] fatal error: Error raised at top level: Abort request error: Bad Request

Identifier: Vapor.Abort.badRequest: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 188
Current stack trace:
0    libswiftCore.dylib                 0x000000010167f130 swift_reportError + 129
1    libswiftCore.dylib                 0x000000010169ba40 _swift_stdlib_reportFatalErrorInFile + 100
2    libswiftCore.dylib                 0x000000010148cba0 (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 124
3    libswiftCore.dylib                 0x0000000101643360 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 93
4    libswiftCore.dylib                 0x000000010148c250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
5    libswiftCore.dylib                 0x0000000101645880 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1) + 144
6    libswiftCore.dylib                 0x000000010148c760 specialized specialized String._withUnsafeBufferPointerToUTF8<A> ((UnsafeBufferPointer<UInt8>) throws -> A) throws -> A + 127
7    libswiftCore.dylib                 0x0000000101606f40 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1) + 185
8    libswiftCore.dylib                 0x000000010148c250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
9    libswiftCore.dylib                 0x00000001015bd130 specialized _assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never + 144
10   libswiftCore.dylib                 0x00000001014b5130 swift_unexpectedError_merged + 289
11   Run                                0x0000000100002350 main + 269
12   libdyld.dylib                      0x00007fffbf407234 start + 1
(lldb)

**Comment by jdmcd** [comment]
Hi! Did you use vaporize to set up the project? Or did you just download it and run it from there?

**Comment by emilagervigstarup** [comment]
Used this:
vapor new CheckInServer --template=mcdappdev/vapor-template

**Comment by jdmcd** [comment]
Gotcha. If you opt not to use Vaporize to setup the template you have to make sure that you manually add mysql.json and redis.json files. See

https://github.com/mcdappdev/vaporize-templates/blob/master/mysql.json and
https://github.com/mcdappdev/vaporize-templates/blob/master/redis.json

Don't forget to replace those values with your values!

**Comment by jdmcd** [comment]
Emil solved this by using Vaporize.
