### ISSUE TITLE
fatal error: Error raised at top level: Configuration error: Config/redis.json

### ISSUE THREAD

**Issue by nhatlee** [mcdappdev/Vapor-Template#9]
Hi, I clone your project then run `vapor xcode`, and edit your `fluent` file to 
`{
    "driver": "postgresql",
    "keyNamingConvention": "snake_case",
    "migrationEntityName": "fluent",
    "pivotNameConnector": "_",
    "autoForeignKeys": true,
    "defaultPageKey": "page",
    "defaultPageSize": 10
}` 
Then hit `run` button on `Xcode`, it build success but got the crash with log is:
`fatal error: Error raised at top level: Configuration error: Config/redis.json required.: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-900.0.65/src/swift/stdlib/public/core/ErrorType.swift, line 187
2017-10-08 11:56:13.169198+0700 Run[21026:136060] fatal error: Error raised at top level: Configuration error: Config/redis.json required.: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-900.0.65/src/swift/stdlib/public/core/ErrorType.swift, line 187` . 
Please help me, what things I am missing to configuration for project?

**Comment by jdmcd** [comment]
Hi @nhatlee, sorry I'm just getting to this - Github did not alert me to this issue. 

It looks like you need to have a Redis config file implemented as well. My template makes heavy use of caching in a persistent store (redis), so the config file is required. There is a way to remove this dependency, but might require a little work to get the setup files to work. 

Does that help?

**Comment by nhatlee** [comment]
Thanks for your reply. I had done my setup for it running success.
